version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://charanhyst:%40Charan2003@devops.epq9ouu.mongodb.net/myAppDB?retryWrites=true&w=majority&appName=Devops
      - PORT=3000
    depends_on:
      - mongodb
    networks:
      - todo-network

  backend-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/todoapp
      - PORT=3000
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - todo-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mongodb_data: 